### ISSUE TITLE
This package will not update and it refuses to uninstall

### ISSUE THREAD

**Issue by alilland** [lee-dohm/language-generic-config#13]
v 1.3.0

console error

```htmlout
Could not resolve 'language-generic-config' to a package path
loadPackage @ <embedded>:23828
activatePackage @ <embedded>:23959
packagesToEnable.forEach.name @ <embedded>:23714
disabledPackagesSubscription.config.onDidChange @ <embedded>:23714
(anonymous) @ <embedded>:21161
module.exports.Emitter.simpleDispatch @ <embedded>:64158
module.exports.Emitter.emit @ <embedded>:64274
module.exports.Config.emitChangeEvent @ <embedded>:21352
module.exports.Config.setRawValue @ <embedded>:21138
module.exports.Config.set @ <embedded>:20716
module.exports.Config.removeAtKeyPath @ <embedded>:20875
module.exports.PackageManager.removePackageNameFromDisabledPackages @ <embedded>:54616
(anonymous) @ <embedded>:54499
exit @ <embedded>:54048
triggerExitCallback @ <embedded>:128060
(anonymous) @ <embedded>:128073
(anonymous) @ <embedded>:127942
emitOne @ events.js:101
emit @ events.js:188
_handle.close @ net.js:501
events.js:101 Uncaught (in promise) Error: Failed to load package 'language-generic-config'
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:686:35)
    at packagesToEnable.forEach.name (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:439:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:439:30)
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:407:18)
    at PackageManager.module.exports.PackageManager.removePackageNameFromDisabledPackages (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:696:32)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:579:25
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

![Alt Text](http://g.recordit.co/YySZTfkIzy.gif)

**Comment by lee-dohm** [comment]
Do you get the same problem if you close Atom and run `apm uninstall language-generic-config` from the terminal?

**Comment by lee-dohm** [comment]
There's nothing in this package that would cause a problem with uninstallation or upgrade. It's a very vanilla package. I suspect this was either something with your configuration or a transient error caused by something else.
